# Generated by Django 5.2.7 on 2025-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='business_type',
            field=models.CharField(choices=[('car_wash', 'Car Wash'), ('barber', 'Barber Shop'), ('spa_salon', 'Spa & Salon'), ('gym', 'Gym & Fitness')], default='car_wash', max_length=50),
        ),
    ]
