# Generated by Django 5.2.7 on 2025-10-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessinfo_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarwashSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_offered', models.TextField(help_text='List the services offered (e.g, body wash, interior cleaning, engine wash )')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('pricing_details', models.TextField(help_text='Provide pricing details for different services')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carwash_setup', to='core.businessinfo')),
            ],
        ),
    ]
