# Generated by Django 5.2.7 on 2025-11-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carwashsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#28a745', max_length=20)),
                ('about', models.TextField(blank=True)),
                ('services', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='core.businessinfo')),
            ],
        ),
    ]
