# Generated by Django 5.2.7 on 2025-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businesswebsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='businessinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='carwashsetup',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='carwashsetup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='carwashsetup',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='carwashsetup',
            name='services_offered',
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='closing_time',
            field=models.TimeField(default='10'),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='location',
            field=models.CharField(default='nairobi', max_length=255),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='pricing_details',
            field=models.TextField(default='10', help_text='Provide pricing details for different services'),
        ),
        migrations.AlterField(
            model_name='businesswebsite',
            name='address',
            field=models.CharField(blank=True, default='13', max_length=255),
        ),
    ]
