# Generated by Django 5.2.7 on 2025-11-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_businessinfo_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashsetup',
            name='pricing_details',
        ),
    ]
