# Generated by Django 5.2.7 on 2025-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_carwashsetup_pricing_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswebsite',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='hero_subtitle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesswebsite',
            name='welcome_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
