# Generated by Django 5.2.7 on 2025-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businesswebsite_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswebsite',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='businesswebsite',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='businesswebsite',
            name='pricing_details',
            field=models.TextField(default='', help_text='Provide pricing details for different services'),
        ),
    ]
